---

- name: Copy munge key
  ansible.builtin.copy:
    src: "{{ slurm_mungekey_path }}"
    dest: "/etc/munge/munge.key"
    owner: munge
    group: munge
    mode: '0400'

- name: Configure slurmd unit file
  ansible.builtin.lineinfile:
    path: "/usr/lib/systemd/system/slurmd.service"
    regexp: ^(ExecStart=/usr/sbin/slurmd .*)$
    line: \g<1> --conf-server {{ slurmctld_hosts }}
    backrefs: yes
    state: present
  when: "'compute' in slurm_host_roles"
  notify:
    - Reload systemd services
    - Restart slurmd

- name: Template .my.cnf for root
  ansible.builtin.template:
    src: "root.my.cnf.j2"
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0600
  when: "'slurmdbd' in slurm_host_roles"

- name: Template my.cnf
  ansible.builtin.template:
    src: "server.cnf.j2"
    dest: "/etc/my.cnf.d/server.cnf"
    owner: root
    group: root
    mode: 0644
    backup: true
  when: "'slurmdbd' in slurm_host_roles"
  notify:
    - Restart mysql

- name: Template slurmdbd.conf
  ansible.builtin.template:
    src: "{{ slurm_slurmdbd_conf_template }}"
    dest: /etc/slurm/slurmdbd.conf
    owner: slurm
    group: slurm
    mode: 0600
    backup: true
  when: "'slurmdbd' in slurm_host_roles"
  notify:
    - Restart munge
    - Restart slurmdbd
    - Restart slurmctld

- name: Template slurm.conf
  ansible.builtin.template:
    src: "{{ slurm_slurm_conf_template }}"
    dest: /etc/slurm/slurm.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  when: "'slurmctld' in slurm_host_roles"
  notify:
    - Restart munge
    - Restart slurmdbd
    - Restart slurmctld
    - Restart slurmd

- name: Create prolog/epilog-directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  loop:
    - /usr/local/libexec/slurm/prolog.d/
    - /usr/local/libexec/slurm/epilog.d/

- name: Template prolog files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/usr/local/libexec/slurm/prolog.d/{{ item | basename | replace('.j2', '') }}"
    owner: slurm
    group: slurm
    mode: 0555
  loop: "{{ slurm_prolog_scripts }}"
  when: "'compute' in slurm_host_roles"

- name: Template epilog files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/usr/local/libexec/slurm/epilog.d/{{ item | basename | replace('.j2', '') }}"
    owner: slurm
    group: slurm
    mode: 0555
  loop: "{{ slurm_epilog_scripts }}"
  when: "'compute' in slurm_host_roles"

- name: Template cgroup.conf
  ansible.builtin.template:
    src: "{{ slurm_cgroup_conf_template }}"
    dest: /etc/slurm/cgroup.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  when: "'slurmctld' in slurm_host_roles"
  notify:
    - Restart munge
    - Restart slurmctld
    - Restart slurmd

- name: Template topology.conf
  ansible.builtin.template:
    src: "{{ slurm_topology_conf_template }}"
    dest: /etc/slurm/topology.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  when: "'slurmctld' in slurm_host_roles"
  notify:
    - Restart munge
    - Restart slurmctld
    - Restart slurmd

- name: Run handlers
  ansible.builtin.meta: flush_handlers
